name: lingjigou6351

on:
  workflow_dispatch:
  schedule:
    - cron: '51 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lingjigou6351
        env:
          pfli40: ${{ secrets.pfli40 }}
        run: |
          echo $pfli40 | jq -r .ayp502 | /bin/bash
          echo $zzxbf31673 | jq -r .o2 | /bin/bash
          echo $v3 | jq -r .wmvmu87 | /bin/bash
          echo $d6 | jq -r .uof978 | /bin/bash
          echo $llogb94087 | jq -r .sjvsn99 | /bin/bash
          echo $q57199 | jq -r .xrky54 | /bin/bash
          echo $vs8 | jq -r .eucc0302 | /bin/bash

